-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'STUDENT_CREATED';
-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'STUDENT_UPDATED';
-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'STUDENT_STATUS_CHANGED';
-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'DEPARTMENT_CREATED';
-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'DEPARTMENT_UPDATED';
-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'CLASS_CREATED';
-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'CLASS_UPDATED';
