-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'EXAM_CANCELLED';
ALTER TYPE "AuditAction" ADD VALUE 'EXAM_CONFLICT_CHECKED';
ALTER TYPE "AuditAction" ADD VALUE 'EXAM_CANDIDATE_ADDED';
ALTER TYPE "AuditAction" ADD VALUE 'EXAM_CANDIDATE_EXCLUDED';
ALTER TYPE "AuditAction" ADD VALUE 'EXAM_CANDIDATE_REINSTATED';